### ISSUE TITLE
Launcher stuck

### ISSUE THREAD

**Issue by themaclanky** [atyourservicesire/launchandfixcod#1]
Hi, I've noticed that If I run the .bat, It just gets stuck here, not sure why: (The battlenet launcher opens, but the game does not start)

![Screenshot_2](https://user-images.githubusercontent.com/66395377/95025180-55bbde00-065e-11eb-9a2b-2fc344f242cf.png)

If I run the .bat with the battlenet launcher open it works normally. It's not a big deal, but I just wanted to let you know

Great work btw!!

**Comment by devjoda** [comment]
Hi @themaclanky 

I tried reproducing the error with no luck. 

When running the script without a b.net instance running, it will try and launch b.net. 

If the "keep me logged in" option in the b.net launcher is checked, login should happen automatically without needing to input credentials (username and password).

If the option is _un_checked however, the scripts default behavior is to wait for the user to input credentials and press the login button, since the script can't launch the game unless the user has logged on to b.net. 

Did you try and input credentials and click the login button? 

If so did you see the following info message in the command line:

> Waiting for user to log on to Battle.net... 

Are you running a Beta version of Battle.net?

**Comment by themaclanky** [comment]
When I uncheck the "keep me logged in" option and enter my credentials, the same thing happens... But yeah, I don't see the 
"Waiting for user to log on to Battle.net" after doing that.

As I said before, the .bat opens the b. net launcher, but does not start the game

Also, I'm not running a beta version

**Comment by devjoda** [comment]
What language do you have selected in the b.net settings under the general tab?

**Comment by themaclanky** [comment]
Oh, seems like that was the problem! I've been using Portuguese as the main language...
Changed it to English and it works now

**Comment by devjoda** [comment]
Great to hear.

I updated the readme file to address the language issue. It also contains some basic instructions for modifying the b.net login process name in order to add support to your local language.
